[build]
  command = "pnpm install"
  publish = "public"
  functions = "netlify/functions"

[functions]
  external_node_modules = [
    "@nestjs/microservices",
    "@nestjs/platform-express",
    "@fastify/view",
    "class-transformer",
    "@nestjs/websockets",
    "argon2",
    "@phc/format",
  ]
  included_files = ["node_modules/argon2/**", "node_modules/@phc/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
