[build]
  command = "pnpm install"
  publish = "public"
  functions = "netlify/functions"

[functions]
  external_node_modules = [
    "@nestjs/microservices",
    "@nestjs/platform-express",
    "@fastify/view",
    "class-transformer",
    "@nestjs/websockets",
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
